export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'


export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const LOGOUT_USER =  'LOGOUT_USER'

export const HANDEL_CHANGE =  'HANDEL_CHANGE'
export const CLEAR_VALUES =  'CLEAR_VALUES'

export const CREATE_NOTE_BEGIN = 'CREATE_NOTE_BEGIN';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR';

export const GET_NOTES_BEGIN = 'GET_NOTES_BEGIN'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'


export const SET_EDIT_NOTE = 'SET_EDIT_NOTE'


export const DELETE_NOTE_BEGIN = 'DELETE_NOTE_BEGIN'

export const DELETE_NOTES_BEGIN = 'DELETE_NOTES_BEGIN'

export const EDIT_NOTE_BEGIN = 'EDIT_NOTE_BEGIN';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR';

export const SET_DARK_MODE = 'SET_DARK_MODE'
